In [1]:
import pandas as pd

In [2]:
s = pd.Series([1,2,3,4,6],index=['a','b','c','d','e'])

In [3]:
s

a    1
b    2
c    3
d    4
e    6
dtype: int64

In [4]:
s.values

array([1, 2, 3, 4, 6], dtype=int64)

In [5]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [6]:
s[2]

3

In [7]:
s['c']

3

In [8]:
s[3:5]

d    4
e    6
dtype: int64

In [9]:
s[['a','e']]

a    1
e    6
dtype: int64

In [10]:
s[1]=0

In [11]:
s

a    1
b    0
c    3
d    4
e    6
dtype: int64

In [12]:
s['b'] =12

In [13]:
s

a     1
b    12
c     3
d     4
e     6
dtype: int64

In [14]:
import numpy as np

In [15]:
arr = np.array([1,2,4,6])

In [16]:
s1 = pd.Series(arr,index=['a','b','c','d'])

In [17]:
s1

a    1
b    2
c    4
d    6
dtype: int32

s4 =pd.Series(s)

In [18]:
s4=pd.Series(s)

In [19]:
s4

a     1
b    12
c     3
d     4
e     6
dtype: int64

In [20]:
arr

array([1, 2, 4, 6])

In [21]:
arr[2]=-3

In [22]:
s1

a    1
b    2
c   -3
d    6
dtype: int32

In [23]:
s

a     1
b    12
c     3
d     4
e     6
dtype: int64

In [24]:
s[s>4]

b    12
e     6
dtype: int64

In [25]:
s/2

a    0.5
b    6.0
c    1.5
d    2.0
e    3.0
dtype: float64

In [26]:
np.log(s4)

a    0.000000
b    2.484907
c    1.098612
d    1.386294
e    1.791759
dtype: float64

In [27]:
serd = pd.Series([1,2,3,4,5,6,7,7,9,3,12],index=['purple','white','green','red','yellow','red','pink','white','red','purple','yellow'])

In [28]:
serd

purple     1
white      2
green      3
red        4
yellow     5
red        6
pink       7
white      7
red        9
purple     3
yellow    12
dtype: int64

In [29]:
serd.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  9, 12], dtype=int64)

In [30]:
serd.value_counts()

3     2
7     2
1     1
2     1
4     1
5     1
6     1
9     1
12    1
dtype: int64

In [31]:
serd.isin([1,3])

purple     True
white     False
green      True
red       False
yellow    False
red       False
pink      False
white     False
red       False
purple     True
yellow    False
dtype: bool

In [32]:
serd[serd.isin([4,3])]

green     3
red       4
purple    3
dtype: int64

In [33]:
s2=pd.Series([1,2,np.NaN,15])

In [34]:
s2

0     1.0
1     2.0
2     NaN
3    15.0
dtype: float64

In [35]:
s2.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [36]:
s2.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [37]:
s2[s2.notnull()]

0     1.0
1     2.0
3    15.0
dtype: float64

In [38]:
s2[s2.isnull()]

2   NaN
dtype: float64

In [39]:
mydict={'red':1000,
       'orange':3000,
       'pink':500,
       'blue':450}

In [40]:
myser=pd.Series(mydict)

In [41]:
myser

red       1000
orange    3000
pink       500
blue       450
dtype: int64

In [42]:
colors=['red','orange','pink','blue','maroon']

In [43]:
myser1=pd.Series(mydict,index=colors)

In [44]:
myser1

red       1000.0
orange    3000.0
pink       500.0
blue       450.0
maroon       NaN
dtype: float64

In [45]:
obj =pd.Series([1,2,3,7])

In [46]:
obj.values

array([1, 2, 3, 7], dtype=int64)

In [47]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [48]:
obj = pd.Series([4,7,3,-5],index=['d','b','a','c'])

In [49]:
obj

d    4
b    7
a    3
c   -5
dtype: int64

In [51]:
obj[['c','a','d']]

c   -5
a    3
d    4
dtype: int64

In [55]:
obj [obj>0]

d    4
b    7
a    3
dtype: int64

In [56]:
np.exp(obj)

d      54.598150
b    1096.633158
a      20.085537
c       0.006738
dtype: float64

In [57]:
sdata = {'Nairobi':45000,
        'Kisumu':30000,
        'Nakuru':10000,
        'Mombasa':16400,
        'Eldoret':80000}

In [58]:
mys_ser=pd.Series(sdata)

In [60]:
mys_ser

Nairobi    45000
Kisumu     30000
Nakuru     10000
Mombasa    16400
Eldoret    80000
dtype: int64

In [61]:
counties=['Migori','Kisii','Uasin_Gishu','Nandi','Kericho']

In [62]:
obj4=pd.Series(sdata,index=counties)

In [63]:
obj4

Migori        NaN
Kisii         NaN
Uasin_Gishu   NaN
Nandi         NaN
Kericho       NaN
dtype: float64

In [70]:
obj4.value=[12000,12500,23000,45000,1000]

In [67]:
obj4

Migori        NaN
Kisii         NaN
Uasin_Gishu   NaN
Nandi         NaN
Kericho       NaN
dtype: float64

In [68]:
obj4

Migori        NaN
Kisii         NaN
Uasin_Gishu   NaN
Nandi         NaN
Kericho       NaN
dtype: float64

In [71]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [72]:
frame = pd.DataFrame(data)

In [73]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [74]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [76]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [78]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])

In [79]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [80]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [81]:
frame.index

RangeIndex(start=0, stop=6, step=1)

In [82]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [83]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [84]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [85]:
frame2['debt']=6.5

In [96]:
frame2['debt']=np.arange(9.,15.)

In [97]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   9.0
two    2001    Ohio  1.7  10.0
three  2002    Ohio  3.6  11.0
four   2001  Nevada  2.4  12.0
five   2002  Nevada  2.9  13.0
six    2003  Nevada  3.2  14.0

In [3]:
sdata = {'Nairobi':35000,
         'Naivasha':45000,
         'Narok':39000,
         'Migori':20000
        }

In [4]:
obj4=pd.Series(sdata)

In [5]:
obj4

Nairobi     35000
Naivasha    45000
Narok       39000
Migori      20000
dtype: int64

In [9]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}


In [10]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [11]:
frame = pd.DataFrame(data)

In [12]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [13]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [14]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [16]:
frame2=pd.DataFrame(data,
                    columns=['year', 'state', 'pop', 'debt'],
                    index=['one', 'two', 'three', 'four','five', 'six'])

In [17]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [18]:
import numpy as np

In [19]:
frame2['debt'] =np.arange(6.)

In [20]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [2]:
import numpy as np

In [3]:
df =pd.read_csv('C:/Users/hp/Desktop/machine_learning_datasets/iris.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/hp/Desktop/machine_learning_datasets/iris.csv'

In [4]:
from sklearn import datasets

In [5]:
iris = datasets.load_iris()

In [10]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [22]:
data = {'state':['Nairobi','Nairobi','Nakuru','Nakuru','Kisumu','Kisumu','Narok','Narok'],
                   'year':[2000,2001,2001,2002,2000,2002,2001,2002],
                   'pop':[12.7,15,10,12,7.5,9,10,11]
                   }

In [23]:
frame=pd.DataFrame(data)

In [24]:
frame

state  year   pop
0  Nairobi  2000  12.7
1  Nairobi  2001  15.0
2   Nakuru  2001  10.0
3   Nakuru  2002  12.0
4   Kisumu  2000   7.5
5   Kisumu  2002   9.0
6    Narok  2001  10.0
7    Narok  2002  11.0

In [28]:
frame.tail(n=3)

state  year   pop
5  Kisumu  2002   9.0
6   Narok  2001  10.0
7   Narok  2002  11.0

In [29]:
pd.DataFrame(data,columns=['year','state','pop'])

year    state   pop
0  2000  Nairobi  12.7
1  2001  Nairobi  15.0
2  2001   Nakuru  10.0
3  2002   Nakuru  12.0
4  2000   Kisumu   7.5
5  2002   Kisumu   9.0
6  2001    Narok  10.0
7  2002    Narok  11.0

In [36]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six','seven','eight'])

In [39]:
frame2['debt'] = np.arange(8.)

In [40]:
frame2

year    state   pop  debt
one    2000  Nairobi  12.7   0.0
two    2001  Nairobi  15.0   1.0
three  2001   Nakuru  10.0   2.0
four   2002   Nakuru  12.0   3.0
five   2000   Kisumu   7.5   4.0
six    2002   Kisumu   9.0   5.0
seven  2001    Narok  10.0   6.0
eight  2002    Narok  11.0   7.0

In [41]:
frame2['year']

one      2000
two      2001
three    2001
four     2002
five     2000
six      2002
seven    2001
eight    2002
Name: year, dtype: int64

In [45]:
type(frame2)

pandas.core.frame.DataFrame

In [46]:
frame2.loc['two']

year        2001
state    Nairobi
pop         15.0
debt         1.0
Name: two, dtype: object

In [47]:
val =pd.Series([-12,-1.74,20],index=['two','five','seven'])

In [48]:
frame3=frame2.copy()

In [49]:
frame3

year    state   pop  debt
one    2000  Nairobi  12.7   0.0
two    2001  Nairobi  15.0   1.0
three  2001   Nakuru  10.0   2.0
four   2002   Nakuru  12.0   3.0
five   2000   Kisumu   7.5   4.0
six    2002   Kisumu   9.0   5.0
seven  2001    Narok  10.0   6.0
eight  2002    Narok  11.0   7.0

In [50]:
frame3['debt']=val

In [51]:
frame3

year    state   pop   debt
one    2000  Nairobi  12.7    NaN
two    2001  Nairobi  15.0 -12.00
three  2001   Nakuru  10.0    NaN
four   2002   Nakuru  12.0    NaN
five   2000   Kisumu   7.5  -1.74
six    2002   Kisumu   9.0    NaN
seven  2001    Narok  10.0  20.00
eight  2002    Narok  11.0    NaN

In [52]:
 pop = {'Nevada': {2001: 2.4, 2002: 2.9},
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [53]:
frame4=pd.DataFrame(pop)

In [54]:
frame4

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [55]:
obj = pd.Series([1.2,4.5,7.3,8.0],index=['a','b','c','d'])

In [56]:
obj

a    1.2
b    4.5
c    7.3
d    8.0
dtype: float64

In [57]:
obj1=obj.reindex(['a','b','c','e','f'])

In [58]:
obj1

a    1.2
b    4.5
c    7.3
e    NaN
f    NaN
dtype: float64

In [59]:
obj2 = pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [60]:
obj2

0      blue
2    purple
4    yellow
dtype: object

In [61]:
obj3=obj2.reindex(range(6),method='ffill')

In [62]:
obj3

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [64]:
fr=pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Utah','Nevada','LA'])

In [65]:
fr

Utah  Nevada  LA
a     0       1   2
c     3       4   5
d     6       7   8

In [66]:
fr1 = fr.reindex(['a','b','c','d'])

In [67]:
fr1

Utah  Nevada   LA
a   0.0     1.0  2.0
b   NaN     NaN  NaN
c   3.0     4.0  5.0
d   6.0     7.0  8.0